// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tutorial/searchReq.proto

package com.example.tutorial.dto;

public final class SearchRequestProto {
  private SearchRequestProto() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SearchRequestOrBuilder
          extends com.google.protobuf.MessageOrBuilder {

    // required .tutorial.SearchRequest.Request request = 1;
    /**
     * <code>required .tutorial.SearchRequest.Request request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>required .tutorial.SearchRequest.Request request = 1;</code>
     */
    SearchRequestProto.SearchRequest.Request getRequest();
    /**
     * <code>required .tutorial.SearchRequest.Request request = 1;</code>
     */
    SearchRequestProto.SearchRequest.RequestOrBuilder getRequestOrBuilder();
  }
  /**
   * Protobuf type {@code tutorial.SearchRequest}
   */
  public static final class SearchRequest extends
          com.google.protobuf.GeneratedMessage
          implements SearchRequestOrBuilder {
    // Use SearchRequest.newBuilder() to construct.
    private SearchRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SearchRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SearchRequest defaultInstance;
    public static SearchRequest getDefaultInstance() {
      return defaultInstance;
    }

    public SearchRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SearchRequest(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                      extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              SearchRequestProto.SearchRequest.Request.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(SearchRequestProto.SearchRequest.Request.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return SearchRequestProto.internal_static_tutorial_SearchRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return SearchRequestProto.internal_static_tutorial_SearchRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      SearchRequestProto.SearchRequest.class, SearchRequestProto.SearchRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<SearchRequest> PARSER =
            new com.google.protobuf.AbstractParser<SearchRequest>() {
              public SearchRequest parsePartialFrom(
                      com.google.protobuf.CodedInputStream input,
                      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                      throws com.google.protobuf.InvalidProtocolBufferException {
                return new SearchRequest(input, extensionRegistry);
              }
            };

    @java.lang.Override
    public com.google.protobuf.Parser<SearchRequest> getParserForType() {
      return PARSER;
    }

    public interface RequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

      // required string PlatCstId = 1;
      /**
       * <code>required string PlatCstId = 1;</code>
       */
      boolean hasPlatCstId();
      /**
       * <code>required string PlatCstId = 1;</code>
       */
      java.lang.String getPlatCstId();
      /**
       * <code>required string PlatCstId = 1;</code>
       */
      com.google.protobuf.ByteString
      getPlatCstIdBytes();

      // required string ChannelNo = 2;
      /**
       * <code>required string ChannelNo = 2;</code>
       */
      boolean hasChannelNo();
      /**
       * <code>required string ChannelNo = 2;</code>
       */
      java.lang.String getChannelNo();
      /**
       * <code>required string ChannelNo = 2;</code>
       */
      com.google.protobuf.ByteString
      getChannelNoBytes();

      // required string TxnDt = 3;
      /**
       * <code>required string TxnDt = 3;</code>
       */
      boolean hasTxnDt();
      /**
       * <code>required string TxnDt = 3;</code>
       */
      java.lang.String getTxnDt();
      /**
       * <code>required string TxnDt = 3;</code>
       */
      com.google.protobuf.ByteString
      getTxnDtBytes();

      // required string TxnTs = 4;
      /**
       * <code>required string TxnTs = 4;</code>
       */
      boolean hasTxnTs();
      /**
       * <code>required string TxnTs = 4;</code>
       */
      java.lang.String getTxnTs();
      /**
       * <code>required string TxnTs = 4;</code>
       */
      com.google.protobuf.ByteString
      getTxnTsBytes();

      // required string TxnSrlNo = 5;
      /**
       * <code>required string TxnSrlNo = 5;</code>
       */
      boolean hasTxnSrlNo();
      /**
       * <code>required string TxnSrlNo = 5;</code>
       */
      java.lang.String getTxnSrlNo();
      /**
       * <code>required string TxnSrlNo = 5;</code>
       */
      com.google.protobuf.ByteString
      getTxnSrlNoBytes();
    }
    /**
     * Protobuf type {@code tutorial.SearchRequest.Request}
     */
    public static final class Request extends
            com.google.protobuf.GeneratedMessage
            implements RequestOrBuilder {
      // Use Request.newBuilder() to construct.
      private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Request defaultInstance;
      public static Request getDefaultInstance() {
        return defaultInstance;
      }

      public Request getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Request(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                        extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                platCstId_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                channelNo_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                txnDt_ = input.readBytes();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                txnTs_ = input.readBytes();
                break;
              }
              case 42: {
                bitField0_ |= 0x00000010;
                txnSrlNo_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return SearchRequestProto.internal_static_tutorial_SearchRequest_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return SearchRequestProto.internal_static_tutorial_SearchRequest_Request_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        SearchRequestProto.SearchRequest.Request.class, SearchRequestProto.SearchRequest.Request.Builder.class);
      }

      public static com.google.protobuf.Parser<Request> PARSER =
              new com.google.protobuf.AbstractParser<Request>() {
                public Request parsePartialFrom(
                        com.google.protobuf.CodedInputStream input,
                        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                        throws com.google.protobuf.InvalidProtocolBufferException {
                  return new Request(input, extensionRegistry);
                }
              };

      @java.lang.Override
      public com.google.protobuf.Parser<Request> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string PlatCstId = 1;
      public static final int PLATCSTID_FIELD_NUMBER = 1;
      private java.lang.Object platCstId_;
      /**
       * <code>required string PlatCstId = 1;</code>
       */
      public boolean hasPlatCstId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string PlatCstId = 1;</code>
       */
      public java.lang.String getPlatCstId() {
        java.lang.Object ref = platCstId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            platCstId_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string PlatCstId = 1;</code>
       */
      public com.google.protobuf.ByteString
      getPlatCstIdBytes() {
        java.lang.Object ref = platCstId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          platCstId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string ChannelNo = 2;
      public static final int CHANNELNO_FIELD_NUMBER = 2;
      private java.lang.Object channelNo_;
      /**
       * <code>required string ChannelNo = 2;</code>
       */
      public boolean hasChannelNo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string ChannelNo = 2;</code>
       */
      public java.lang.String getChannelNo() {
        java.lang.Object ref = channelNo_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            channelNo_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string ChannelNo = 2;</code>
       */
      public com.google.protobuf.ByteString
      getChannelNoBytes() {
        java.lang.Object ref = channelNo_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          channelNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string TxnDt = 3;
      public static final int TXNDT_FIELD_NUMBER = 3;
      private java.lang.Object txnDt_;
      /**
       * <code>required string TxnDt = 3;</code>
       */
      public boolean hasTxnDt() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string TxnDt = 3;</code>
       */
      public java.lang.String getTxnDt() {
        java.lang.Object ref = txnDt_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            txnDt_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string TxnDt = 3;</code>
       */
      public com.google.protobuf.ByteString
      getTxnDtBytes() {
        java.lang.Object ref = txnDt_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          txnDt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string TxnTs = 4;
      public static final int TXNTS_FIELD_NUMBER = 4;
      private java.lang.Object txnTs_;
      /**
       * <code>required string TxnTs = 4;</code>
       */
      public boolean hasTxnTs() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string TxnTs = 4;</code>
       */
      public java.lang.String getTxnTs() {
        java.lang.Object ref = txnTs_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            txnTs_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string TxnTs = 4;</code>
       */
      public com.google.protobuf.ByteString
      getTxnTsBytes() {
        java.lang.Object ref = txnTs_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          txnTs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // required string TxnSrlNo = 5;
      public static final int TXNSRLNO_FIELD_NUMBER = 5;
      private java.lang.Object txnSrlNo_;
      /**
       * <code>required string TxnSrlNo = 5;</code>
       */
      public boolean hasTxnSrlNo() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string TxnSrlNo = 5;</code>
       */
      public java.lang.String getTxnSrlNo() {
        java.lang.Object ref = txnSrlNo_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            txnSrlNo_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string TxnSrlNo = 5;</code>
       */
      public com.google.protobuf.ByteString
      getTxnSrlNoBytes() {
        java.lang.Object ref = txnSrlNo_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (java.lang.String) ref);
          txnSrlNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        platCstId_ = "";
        channelNo_ = "";
        txnDt_ = "";
        txnTs_ = "";
        txnSrlNo_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasPlatCstId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasChannelNo()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTxnDt()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTxnTs()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasTxnSrlNo()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
              throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getPlatCstIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getChannelNoBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getTxnDtBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getTxnTsBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeBytes(5, getTxnSrlNoBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
                  .computeBytesSize(1, getPlatCstIdBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
                  .computeBytesSize(2, getChannelNoBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
                  .computeBytesSize(3, getTxnDtBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
                  .computeBytesSize(4, getTxnTsBytes());
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
                  .computeBytesSize(5, getTxnSrlNoBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
              throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static SearchRequestProto.SearchRequest.Request parseFrom(
              com.google.protobuf.ByteString data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static SearchRequestProto.SearchRequest.Request parseFrom(
              com.google.protobuf.ByteString data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static SearchRequestProto.SearchRequest.Request parseFrom(byte[] data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static SearchRequestProto.SearchRequest.Request parseFrom(
              byte[] data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static SearchRequestProto.SearchRequest.Request parseFrom(java.io.InputStream input)
              throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static SearchRequestProto.SearchRequest.Request parseFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static SearchRequestProto.SearchRequest.Request parseDelimitedFrom(java.io.InputStream input)
              throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static SearchRequestProto.SearchRequest.Request parseDelimitedFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static SearchRequestProto.SearchRequest.Request parseFrom(
              com.google.protobuf.CodedInputStream input)
              throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static SearchRequestProto.SearchRequest.Request parseFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(SearchRequestProto.SearchRequest.Request prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code tutorial.SearchRequest.Request}
       */
      public static final class Builder extends
              com.google.protobuf.GeneratedMessage.Builder<Builder>
              implements SearchRequestProto.SearchRequest.RequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
          return SearchRequestProto.internal_static_tutorial_SearchRequest_Request_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
          return SearchRequestProto.internal_static_tutorial_SearchRequest_Request_fieldAccessorTable
                  .ensureFieldAccessorsInitialized(
                          SearchRequestProto.SearchRequest.Request.class, SearchRequestProto.SearchRequest.Request.Builder.class);
        }

        // Construct using com.example.tutorial.SearchRequestProto.SearchRequest.Request.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          platCstId_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          channelNo_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          txnDt_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          txnTs_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          txnSrlNo_ = "";
          bitField0_ = (bitField0_ & ~0x00000010);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
          return SearchRequestProto.internal_static_tutorial_SearchRequest_Request_descriptor;
        }

        public SearchRequestProto.SearchRequest.Request getDefaultInstanceForType() {
          return SearchRequestProto.SearchRequest.Request.getDefaultInstance();
        }

        public SearchRequestProto.SearchRequest.Request build() {
          SearchRequestProto.SearchRequest.Request result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public SearchRequestProto.SearchRequest.Request buildPartial() {
          SearchRequestProto.SearchRequest.Request result = new SearchRequestProto.SearchRequest.Request(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.platCstId_ = platCstId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.channelNo_ = channelNo_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.txnDt_ = txnDt_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.txnTs_ = txnTs_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.txnSrlNo_ = txnSrlNo_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof SearchRequestProto.SearchRequest.Request) {
            return mergeFrom((SearchRequestProto.SearchRequest.Request)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(SearchRequestProto.SearchRequest.Request other) {
          if (other == SearchRequestProto.SearchRequest.Request.getDefaultInstance()) return this;
          if (other.hasPlatCstId()) {
            bitField0_ |= 0x00000001;
            platCstId_ = other.platCstId_;
            onChanged();
          }
          if (other.hasChannelNo()) {
            bitField0_ |= 0x00000002;
            channelNo_ = other.channelNo_;
            onChanged();
          }
          if (other.hasTxnDt()) {
            bitField0_ |= 0x00000004;
            txnDt_ = other.txnDt_;
            onChanged();
          }
          if (other.hasTxnTs()) {
            bitField0_ |= 0x00000008;
            txnTs_ = other.txnTs_;
            onChanged();
          }
          if (other.hasTxnSrlNo()) {
            bitField0_ |= 0x00000010;
            txnSrlNo_ = other.txnSrlNo_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasPlatCstId()) {

            return false;
          }
          if (!hasChannelNo()) {

            return false;
          }
          if (!hasTxnDt()) {

            return false;
          }
          if (!hasTxnTs()) {

            return false;
          }
          if (!hasTxnSrlNo()) {

            return false;
          }
          return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
          SearchRequestProto.SearchRequest.Request parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (SearchRequestProto.SearchRequest.Request) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string PlatCstId = 1;
        private java.lang.Object platCstId_ = "";
        /**
         * <code>required string PlatCstId = 1;</code>
         */
        public boolean hasPlatCstId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string PlatCstId = 1;</code>
         */
        public java.lang.String getPlatCstId() {
          java.lang.Object ref = platCstId_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                    .toStringUtf8();
            platCstId_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string PlatCstId = 1;</code>
         */
        public com.google.protobuf.ByteString
        getPlatCstIdBytes() {
          java.lang.Object ref = platCstId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            platCstId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string PlatCstId = 1;</code>
         */
        public Builder setPlatCstId(
                java.lang.String value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          platCstId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string PlatCstId = 1;</code>
         */
        public Builder clearPlatCstId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          platCstId_ = getDefaultInstance().getPlatCstId();
          onChanged();
          return this;
        }
        /**
         * <code>required string PlatCstId = 1;</code>
         */
        public Builder setPlatCstIdBytes(
                com.google.protobuf.ByteString value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          platCstId_ = value;
          onChanged();
          return this;
        }

        // required string ChannelNo = 2;
        private java.lang.Object channelNo_ = "";
        /**
         * <code>required string ChannelNo = 2;</code>
         */
        public boolean hasChannelNo() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string ChannelNo = 2;</code>
         */
        public java.lang.String getChannelNo() {
          java.lang.Object ref = channelNo_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                    .toStringUtf8();
            channelNo_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string ChannelNo = 2;</code>
         */
        public com.google.protobuf.ByteString
        getChannelNoBytes() {
          java.lang.Object ref = channelNo_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            channelNo_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string ChannelNo = 2;</code>
         */
        public Builder setChannelNo(
                java.lang.String value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          channelNo_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string ChannelNo = 2;</code>
         */
        public Builder clearChannelNo() {
          bitField0_ = (bitField0_ & ~0x00000002);
          channelNo_ = getDefaultInstance().getChannelNo();
          onChanged();
          return this;
        }
        /**
         * <code>required string ChannelNo = 2;</code>
         */
        public Builder setChannelNoBytes(
                com.google.protobuf.ByteString value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000002;
          channelNo_ = value;
          onChanged();
          return this;
        }

        // required string TxnDt = 3;
        private java.lang.Object txnDt_ = "";
        /**
         * <code>required string TxnDt = 3;</code>
         */
        public boolean hasTxnDt() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string TxnDt = 3;</code>
         */
        public java.lang.String getTxnDt() {
          java.lang.Object ref = txnDt_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                    .toStringUtf8();
            txnDt_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string TxnDt = 3;</code>
         */
        public com.google.protobuf.ByteString
        getTxnDtBytes() {
          java.lang.Object ref = txnDt_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            txnDt_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string TxnDt = 3;</code>
         */
        public Builder setTxnDt(
                java.lang.String value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000004;
          txnDt_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string TxnDt = 3;</code>
         */
        public Builder clearTxnDt() {
          bitField0_ = (bitField0_ & ~0x00000004);
          txnDt_ = getDefaultInstance().getTxnDt();
          onChanged();
          return this;
        }
        /**
         * <code>required string TxnDt = 3;</code>
         */
        public Builder setTxnDtBytes(
                com.google.protobuf.ByteString value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000004;
          txnDt_ = value;
          onChanged();
          return this;
        }

        // required string TxnTs = 4;
        private java.lang.Object txnTs_ = "";
        /**
         * <code>required string TxnTs = 4;</code>
         */
        public boolean hasTxnTs() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required string TxnTs = 4;</code>
         */
        public java.lang.String getTxnTs() {
          java.lang.Object ref = txnTs_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                    .toStringUtf8();
            txnTs_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string TxnTs = 4;</code>
         */
        public com.google.protobuf.ByteString
        getTxnTsBytes() {
          java.lang.Object ref = txnTs_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            txnTs_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string TxnTs = 4;</code>
         */
        public Builder setTxnTs(
                java.lang.String value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000008;
          txnTs_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string TxnTs = 4;</code>
         */
        public Builder clearTxnTs() {
          bitField0_ = (bitField0_ & ~0x00000008);
          txnTs_ = getDefaultInstance().getTxnTs();
          onChanged();
          return this;
        }
        /**
         * <code>required string TxnTs = 4;</code>
         */
        public Builder setTxnTsBytes(
                com.google.protobuf.ByteString value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000008;
          txnTs_ = value;
          onChanged();
          return this;
        }

        // required string TxnSrlNo = 5;
        private java.lang.Object txnSrlNo_ = "";
        /**
         * <code>required string TxnSrlNo = 5;</code>
         */
        public boolean hasTxnSrlNo() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>required string TxnSrlNo = 5;</code>
         */
        public java.lang.String getTxnSrlNo() {
          java.lang.Object ref = txnSrlNo_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                    .toStringUtf8();
            txnSrlNo_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string TxnSrlNo = 5;</code>
         */
        public com.google.protobuf.ByteString
        getTxnSrlNoBytes() {
          java.lang.Object ref = txnSrlNo_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            txnSrlNo_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string TxnSrlNo = 5;</code>
         */
        public Builder setTxnSrlNo(
                java.lang.String value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000010;
          txnSrlNo_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string TxnSrlNo = 5;</code>
         */
        public Builder clearTxnSrlNo() {
          bitField0_ = (bitField0_ & ~0x00000010);
          txnSrlNo_ = getDefaultInstance().getTxnSrlNo();
          onChanged();
          return this;
        }
        /**
         * <code>required string TxnSrlNo = 5;</code>
         */
        public Builder setTxnSrlNoBytes(
                com.google.protobuf.ByteString value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000010;
          txnSrlNo_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:tutorial.SearchRequest.Request)
      }

      static {
        defaultInstance = new Request(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:tutorial.SearchRequest.Request)
    }

    private int bitField0_;
    // required .tutorial.SearchRequest.Request request = 1;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private SearchRequestProto.SearchRequest.Request request_;
    /**
     * <code>required .tutorial.SearchRequest.Request request = 1;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .tutorial.SearchRequest.Request request = 1;</code>
     */
    public SearchRequestProto.SearchRequest.Request getRequest() {
      return request_;
    }
    /**
     * <code>required .tutorial.SearchRequest.Request request = 1;</code>
     */
    public SearchRequestProto.SearchRequest.RequestOrBuilder getRequestOrBuilder() {
      return request_;
    }

    private void initFields() {
      request_ = SearchRequestProto.SearchRequest.Request.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRequest()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getRequest().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, request_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
                .computeMessageSize(1, request_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
            throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SearchRequestProto.SearchRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchRequestProto.SearchRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchRequestProto.SearchRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SearchRequestProto.SearchRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SearchRequestProto.SearchRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SearchRequestProto.SearchRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SearchRequestProto.SearchRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SearchRequestProto.SearchRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SearchRequestProto.SearchRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SearchRequestProto.SearchRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SearchRequestProto.SearchRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tutorial.SearchRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
            implements SearchRequestProto.SearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return SearchRequestProto.internal_static_tutorial_SearchRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return SearchRequestProto.internal_static_tutorial_SearchRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        SearchRequestProto.SearchRequest.class, SearchRequestProto.SearchRequest.Builder.class);
      }

      // Construct using com.example.tutorial.SearchRequestProto.SearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = SearchRequestProto.SearchRequest.Request.getDefaultInstance();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return SearchRequestProto.internal_static_tutorial_SearchRequest_descriptor;
      }

      public SearchRequestProto.SearchRequest getDefaultInstanceForType() {
        return SearchRequestProto.SearchRequest.getDefaultInstance();
      }

      public SearchRequestProto.SearchRequest build() {
        SearchRequestProto.SearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SearchRequestProto.SearchRequest buildPartial() {
        SearchRequestProto.SearchRequest result = new SearchRequestProto.SearchRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SearchRequestProto.SearchRequest) {
          return mergeFrom((SearchRequestProto.SearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SearchRequestProto.SearchRequest other) {
        if (other == SearchRequestProto.SearchRequest.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRequest()) {

          return false;
        }
        if (!getRequest().isInitialized()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        SearchRequestProto.SearchRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SearchRequestProto.SearchRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .tutorial.SearchRequest.Request request = 1;
      private SearchRequestProto.SearchRequest.Request request_ = SearchRequestProto.SearchRequest.Request.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
              SearchRequestProto.SearchRequest.Request, SearchRequestProto.SearchRequest.Request.Builder, SearchRequestProto.SearchRequest.RequestOrBuilder> requestBuilder_;
      /**
       * <code>required .tutorial.SearchRequest.Request request = 1;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .tutorial.SearchRequest.Request request = 1;</code>
       */
      public SearchRequestProto.SearchRequest.Request getRequest() {
        if (requestBuilder_ == null) {
          return request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>required .tutorial.SearchRequest.Request request = 1;</code>
       */
      public Builder setRequest(SearchRequestProto.SearchRequest.Request value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tutorial.SearchRequest.Request request = 1;</code>
       */
      public Builder setRequest(
              SearchRequestProto.SearchRequest.Request.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tutorial.SearchRequest.Request request = 1;</code>
       */
      public Builder mergeRequest(SearchRequestProto.SearchRequest.Request value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
                  request_ != SearchRequestProto.SearchRequest.Request.getDefaultInstance()) {
            request_ =
                    SearchRequestProto.SearchRequest.Request.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .tutorial.SearchRequest.Request request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = SearchRequestProto.SearchRequest.Request.getDefaultInstance();
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .tutorial.SearchRequest.Request request = 1;</code>
       */
      public SearchRequestProto.SearchRequest.Request.Builder getRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>required .tutorial.SearchRequest.Request request = 1;</code>
       */
      public SearchRequestProto.SearchRequest.RequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_;
        }
      }
      /**
       * <code>required .tutorial.SearchRequest.Request request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
              SearchRequestProto.SearchRequest.Request, SearchRequestProto.SearchRequest.Request.Builder, SearchRequestProto.SearchRequest.RequestOrBuilder>
      getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                  SearchRequestProto.SearchRequest.Request, SearchRequestProto.SearchRequest.Request.Builder, SearchRequestProto.SearchRequest.RequestOrBuilder>(
                  request_,
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tutorial.SearchRequest)
    }

    static {
      defaultInstance = new SearchRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:tutorial.SearchRequest)
  }

  private static com.google.protobuf.Descriptors.Descriptor
          internal_static_tutorial_SearchRequest_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_tutorial_SearchRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
          internal_static_tutorial_SearchRequest_Request_descriptor;
  private static
  com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internal_static_tutorial_SearchRequest_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    java.lang.String[] descriptorData = {
            "\n\030tutorial/searchReq.proto\022\010tutorial\"\242\001\n" +
                    "\rSearchRequest\0220\n\007request\030\001 \002(\0132\037.tutori" +
                    "al.SearchRequest.Request\032_\n\007Request\022\021\n\tP" +
                    "latCstId\030\001 \002(\t\022\021\n\tChannelNo\030\002 \002(\t\022\r\n\005Txn" +
                    "Dt\030\003 \002(\t\022\r\n\005TxnTs\030\004 \002(\t\022\020\n\010TxnSrlNo\030\005 \002(" +
                    "\tB*\n\024com.example.tutorialB\022SearchRequest" +
                    "Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                internal_static_tutorial_SearchRequest_descriptor =
                        getDescriptor().getMessageTypes().get(0);
                internal_static_tutorial_SearchRequest_fieldAccessorTable = new
                        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_tutorial_SearchRequest_descriptor,
                        new java.lang.String[] { "Request", });
                internal_static_tutorial_SearchRequest_Request_descriptor =
                        internal_static_tutorial_SearchRequest_descriptor.getNestedTypes().get(0);
                internal_static_tutorial_SearchRequest_Request_fieldAccessorTable = new
                        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                        internal_static_tutorial_SearchRequest_Request_descriptor,
                        new java.lang.String[] { "PlatCstId", "ChannelNo", "TxnDt", "TxnTs", "TxnSrlNo", });
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
